---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-resources
spec:
  project: cluster-management
  source:
    repoURL: https://github.com/operate-first/apps.git
    targetRevision: HEAD
    # path: implement in an overlay
  destination:
    server: in-cluster
    namespace: argocd
  syncPolicy:
    syncOptions:
      - Validate=false
